
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";

const TopProducts = () => {
  const productData = [
    { name: "Women's Denim Jeans", sales: 234, revenue: 14040 },
    { name: "Cotton T-Shirt", sales: 189, revenue: 3780 },
    { name: "Leather Jacket", sales: 156, revenue: 23400 },
    { name: "Summer Dress", sales: 143, revenue: 8580 },
    { name: "Running Shoes", sales: 128, revenue: 9600 },
    { name: "Casual Sneakers", sales: 98, revenue: 7840 },
    { name: "Polo Shirt", sales: 87, revenue: 2175 },
    { name: "Denim Jacket", sales: 76, revenue: 6080 }
  ];

  return (
    <Card className="border-0 shadow-lg">
      <CardHeader>
        <CardTitle className="text-lg font-semibold">Product Sales Comparison</CardTitle>
        <CardDescription>Units sold vs revenue generated by product</CardDescription>
      </CardHeader>
      <CardContent>
        <ResponsiveContainer width="100%" height={400}>
          <BarChart data={productData} margin={{ top: 20, right: 30, left: 20, bottom: 60 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#e0e7ff" />
            <XAxis 
              dataKey="name" 
              stroke="#6b7280"
              angle={-45}
              textAnchor="end"
              height={100}
              fontSize={12}
            />
            <YAxis stroke="#6b7280" />
            <Tooltip 
              contentStyle={{ 
                backgroundColor: 'white', 
                border: '1px solid #e5e7eb',
                borderRadius: '8px',
                boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
              }}
            />
            <Bar dataKey="sales" fill="#3b82f6" radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
};

export default TopProducts;
