// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyynldalizwrygvbtucu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5eW5sZGFsaXp3cnlndmJ0dWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDUyOTMsImV4cCI6MjA2NTI4MTI5M30.Ga3Y3kMZRy6IZO5BFIWjs3hp8HNMIrSpDB0Ik952k2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);